CREATE TYPE GameStatus AS ENUM ('IN_PROGRESS','FIRST_PLAYER_WON','SECOND_PLAYER_WON','FINISHED');
CREATE SEQUENCE player_sequence;
CREATE SEQUENCE move_sequence;
CREATE SEQUENCE game_sequence;
CREATE TABLE PLAYER(
ID INT PRIMARY KEY NOT NULL,
player_name VARCHAR
);
CREATE TABLE GAME(
ID INT PRIMARY KEY NOT NULL,
GAME_NAME VARCHAR NOT NULL,
second_player_id INT NOT NULL,
first_player_id INT NOT NULL,
GAMESTATUS GameStatus,
CREATED DATE
);
CREATE TABLE MOVE(
ID INT PRIMARY KEY NOT NULL,
game_id INT NOT NULL,
board_row INT NOT NULL,
board_column INT NOT NULL,
player_id INT NOT NULL,
created DATE
);